language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t ju11an0/react-test -f client/Dockerfile.dev client

script:
  - docker run -e CI=true ju11an0/react-test npm test

after_success:
  - docker build -t ju11an0/multi-client client
  - docker build -t ju11an0/multi-nginx nginx
  - docker build -t ju11an0/multi-server server
  - docker build -t ju11an0/multi-worker worker
  - echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_ID} --password-stdin
  - docker push ju11an0/multi-client
  - docker push ju11an0/multi-nginx
  - docker push ju11an0/multi-server
  - docker push ju11an0/multi-worker
